############## 动态配置 ##############
db:
  url: @pingpong.db.order.url@
  username: @pingpong.db.order.username@
  password: @pingpong.db.order.password@
tcc:
  db:
    url: @pingpong.db.tcc.url@
    username: @pingpong.db.tcc.username@
    password: @pingpong.db.tcc.password@
dubbo.order:
  name: @pingpongx.dubbo.order.name@
  registry.address: @pingpongx.dubbo.order.address@
  protocol.port: @pingpongx.dubbo.order.port@

####################################################################################
####################################################################################
############## 以下为固定配置 ##############

ppx:
  environment: @ppx.environment@
  name: tcc-transaction-order

# datasource & mvc & http encoding.
spring:
  dubbo:
    application:
      name: ${dubbo.order.name}
    protocol:
      name: dubbo
      port: ${dubbo.order.protocol.port}
    registry:
      protocol: zookeeper
      address: ${dubbo.order.registry.address}

  #配置数据库 druid
  datasource:
    druid:
      # jdbc配置
      url: jdbc:mysql://${db.url}?useUnicode=true&characterEncoding=utf-8
      username: ${db.username}
      password: ${db.password}
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池配置 (# https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8)
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: false
        wall:
          enabled: true
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

#使用 log4j2
logging:
  config: classpath:log4j2/log4j2-${ppx.environment}.xml
